import Foundation

/// Renders a `ServerInstance` into a copyparty config file (the `-c` format).
///
/// Format reference (verified against copyparty 1.20.16 docs/example.conf):
///   [global]            keys are long flag names minus dashes
///     p: 3923, 8080
///     e2dsa
///   [accounts]
///     ed: 123
///   [/url]
///     /fs/path
///     accs:
///       rw: ed
///     flags:
///       e2d
///
/// Indentation: 2 spaces for section keys, 4 spaces for accs/flags children.
enum ConfigWriter {

    static func config(for server: ServerInstance) -> String {
        var out = "# Generated by CopyParty.app — do not edit by hand.\n"
        out += "# Server: \(server.name)\n\n"
        out += globalSection(server)
        out += accountsSection(server)
        for vol in server.volumes {
            out += volumeSection(vol)
        }
        return out
    }

    // MARK: - [global]

    private static func globalSection(_ s: ServerInstance) -> String {
        var lines: [String] = []
        let p = s.protocols

        // Listen ports / interface
        let ports = p.httpPorts.map(String.init).joined(separator: ", ")
        if !ports.isEmpty { lines.append("p: \(ports)") }
        let ip = p.listenIP.trimmingCharacters(in: .whitespaces)
        if !ip.isEmpty && ip != "0.0.0.0" { lines.append("i: \(ip)") }

        // TLS
        switch p.tlsMode {
        case .auto: break
        case .httpOnly: lines.append("http-only")
        case .httpsOnly: lines.append("https-only")
        }
        let cert = p.certPath.trimmingCharacters(in: .whitespaces)
        if !cert.isEmpty { lines.append("cert: \(cert)") }
        if p.disableAutoCert { lines.append("no-crt") }

        // WebDAV
        if !p.webdavEnabled { lines.append("no-dav") }
        if p.webdavForceAuth { lines.append("dav-auth") }

        // FTP / FTPS
        if p.ftpEnabled { lines.append("ftp: \(p.ftpPort)") }
        if p.ftpsEnabled { lines.append("ftps: \(p.ftpsPort)") }
        if (p.ftpEnabled || p.ftpsEnabled) {
            let nat = p.ftpNAT.trimmingCharacters(in: .whitespaces)
            if !nat.isEmpty { lines.append("ftp-nat: \(nat)") }
            let pr = p.ftpPassiveRange.trimmingCharacters(in: .whitespaces)
            if !pr.isEmpty { lines.append("ftp-pr: \(pr)") }
        }

        // SFTP (needs bundled paramiko)
        if p.sftpEnabled {
            lines.append("sftp: \(p.sftpPort)")
            if p.sftpAllowPassword { lines.append("sftp-pw") }
        }

        // TFTP
        if p.tftpEnabled { lines.append("tftp: \(p.tftpPort)") }

        // SMB
        if p.smbEnabled {
            lines.append("smb")
            if p.smbWritable { lines.append("smbw") }
            if p.smbPort != 445 { lines.append("smb-port: \(p.smbPort)") }
        }

        // Discovery
        if p.zeroconfEnabled { lines.append("z") }
        if p.mdnsAnnounce { lines.append("zm") }
        if p.showQR { lines.append("qr") }

        // Global indexing / misc
        let name = s.global.serverName.trimmingCharacters(in: .whitespaces)
        if !name.isEmpty { lines.append("name: \(name)") }
        if s.global.indexUploads { lines.append("e2dsa") }
        if s.global.indexTags { lines.append("e2ts") }
        if s.global.disableThumbnails { lines.append("no-thumb") }
        if s.global.requireUsername { lines.append("usernames") }
        if s.global.maxClients != 1024 { lines.append("nc: \(s.global.maxClients)") }

        for raw in s.global.extraFlags.split(whereSeparator: \.isNewline) {
            let t = raw.trimmingCharacters(in: .whitespaces)
            if !t.isEmpty { lines.append(t) }
        }

        guard !lines.isEmpty else { return "" }
        return "[global]\n" + lines.map { "  \($0)" }.joined(separator: "\n") + "\n\n"
    }

    // MARK: - [accounts]

    private static func accountsSection(_ s: ServerInstance) -> String {
        let valid = s.accounts.filter {
            !$0.username.trimmingCharacters(in: .whitespaces).isEmpty
        }
        guard !valid.isEmpty else { return "" }
        var out = "[accounts]\n"
        for acct in valid {
            out += "  \(acct.username): \(acct.password)\n"
        }
        return out + "\n"
    }

    // MARK: - [/volume]

    private static func volumeSection(_ v: Volume) -> String {
        let url = v.urlPath.hasPrefix("/") ? v.urlPath : "/\(v.urlPath)"
        var out = "[\(url)]\n"
        out += "  \(v.fsPath)\n"

        let rules = v.access.filter { !$0.permissionKey.isEmpty && !$0.principalsString.isEmpty }
        if !rules.isEmpty {
            out += "  accs:\n"
            for rule in rules {
                out += "    \(rule.permissionKey): \(rule.principalsString)\n"
            }
        }

        let flags = v.flags.map { $0.trimmingCharacters(in: .whitespaces) }.filter { !$0.isEmpty }
        if !flags.isEmpty {
            out += "  flags:\n"
            for flag in flags {
                out += "    \(flag)\n"
            }
        }
        return out + "\n"
    }
}
